name = "my-worker"
type = "webpack"
account_id = "2cdb8330894945d94acbf1ee20001547"
workers_dev = true

[build]
command = "npm run build"
output = "public"
publish = true

[site]
bucket = "./public"
entry-point = "worker"

[routes]
{ pattern = "https://creditoja.pages.dev/*", script = "my-worker" }


