name = "my-worker"
type = "webpack"
account_id = "2cdb8330894945d94acbf1ee20001547"
workers_dev = true

[build]
command = "npm run build"
main = "./public/index.js"
output = "public"
publish = true
watch = ["src", "webpack.config.js"]
routes = [{ pattern = "https://example.com/*", script = "my-worker" }]

[site]
bucket = "./public"
entry-point = "worker"


