name = "my-worker"
type = "webpack"
account_id = "2cdb8330894945d94acbf1ee20001547"
workers_dev = true

[build]
command = "npm run build"
main = "./build/index.js"
output = "build"
publish = true
routes = [{ pattern = "https://creditoja.pages.dev/*", script = "my-worker" }]

[site]
bucket = "./build"
entry-point = "worker"


