name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Update Git
        run: |
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install git

      - name: Configure Git author identity
        run: |
          git config --global user.email "jbc@icomp.ufam.edu.br"
          git config --global user.name "jonathasborges1"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: 🔨 Build application
        env:
          NODE_ENV: production
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        run: |
          echo "export REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> $GITHUB_ENV
          npm run build

      - name: Deploy to GitHub Pages
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        run: |
          npm install -g gh-pages
          gh-pages -d build
