name: 🚀 Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: 🔨 Build application
        env:
          NODE_ENV: production
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "export API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          npm run build