name: 🚀 Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: 🔨 Build application
        env:
          NODE_ENV: production
          API_KEY: ${{ secrets.API_KEY }}
        run: npm run build

      - name: Stage build files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git rm -r ./*
          git add -f build/*
          git commit -m "Add build files"

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN_GITHUB }}
          external_repository: jonathasborges1/creditoja
          publish_dir: ./
          cname: jonathasborges1.github.io
          commit_message: "Deploy to GitHub Pages"