name: Deploy with CloudFlare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build worker
        run: npm run build

      - name: Publish worker
        run: npx wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}